<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="App.Domain\**\*.cs" />
    <Compile Remove="App.Application\**\*.cs" />
    <Compile Remove="App.Infrastructure\**\*.cs" />
    <Compile Remove="App.IOC\**\*.cs" />
    <Compile Remove="App.Domain.Test\**\*.cs" />
    <Compile Remove="App.Application.Test\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="App.Domain\**\*" />
    <Content Remove="App.Application\**\*" />
    <Content Remove="App.Infrastructure\**\*" />
    <Content Remove="App.IOC\**\*" />
    <Content Remove="App.Domain.Test\**\*" />
    <Content Remove="App.Application.Test\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="App.IOC\App.IOC.csproj" />
  </ItemGroup>

</Project>
