<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App.Infrastructure\App.Infrastructure.csproj" />
    <ProjectReference Include="..\App.Application\App.Application.csproj" />
  </ItemGroup>

</Project>
